import json
import polars as pl
import nflreadpy as nfl
from pathlib import Path
from typing import Literal

ISummaryLevel = Literal["week", "reg", "post", "reg+post"]

def parse_qbs(summaryLevel: ISummaryLevel, triggerFileName: str, outputFileName: str, outputConstName: str):
    """
    Fetch current-season QB stats and write them to scripts/qb-data.ts
    """
    try:
        # Fetch player stats (current season by default)
        player_stats = nfl.load_player_stats(summary_level=summaryLevel)

        # Filter to QBs
        qb_data = (
            player_stats
            .filter(pl.col("position") == "QB")
            .to_dicts()
        )

        # Write the data to a TypeScript file
        output_path = Path("scripts/weekly/generated-files") / f"{outputFileName}.ts"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("// file generated by " + triggerFileName + ".py\n\n")
            f.write("export const " + outputConstName + " = ")
            json.dump(qb_data, f, indent=2)
            f.write(";\n")

        print(f"Created file {output_path} with {len(qb_data)} QBs")

    except Exception as e:
        print(f"ERROR: {e}")
        raise
