import json
import logging
import nflreadpy as nfl
from pathlib import Path
from typing import Literal

IPostTeam = Literal[
  "ARI",
  "ATL",
  "BAL",
  "BUF",
  "CAR",
  "CHI",
  "CIN",
  "CLE",
  "DAL",
  "DEN",
  "DET",
  "GB",
  "HOU",
  "IND",
  "JAX",
  "KC",
  "LA",
  "LAC",
  "LAR",
  "LV",
  "MIA",
  "MIN",
  "NE",
  "NO",
  "NYG",
  "NYJ",
  "OAK",
  "PHI",
  "PIT",
  "SD",
  "SEA",
  "SF",
  "STL",
  "TB",
  "TEN",
  "WAS",
  ]

def parse_pbp_qb(posteam: IPostTeam, week: int):
  """
    Generate QB pass play-by-play data for a team and week, and export it as a TypeScript file.
  """
  try:
    pbp_qb_stats = nfl.load_pbp()

    columns = [
    "game_id",
    "play_id",
    "yardline_100",
    "drive",
    "passer",
    "touchdown",
    "qtr",
    "sp",
    "down",
    "yrdln",
    "ydstogo",
    "ydsnet",
    "yards_gained",
    "pass_length",
    "pass_location",
    "air_yards",
    "first_down_pass",
    "incomplete_pass",
    "interception",
    "complete_pass",
    "passer_player_id",
    "passer_player_name",
    "passing_yards",
    "receiver_player_id",
    "receiver_player_name",
    "series",
    "stadium",
    "weather",
    "location",
    "receiver",
    "receiver_jersey_number",
    "name",
    "jersey_number"
]

    filtered = pbp_qb_stats.filter(
      (pbp_qb_stats["posteam"] == posteam) &
      (pbp_qb_stats["pass"] == 1) &
      (pbp_qb_stats["play_type_nfl"] == "PASS") &
      (pbp_qb_stats["week"] == week)
    ).select(columns).to_dicts()

    # Write the data to a TypeScript file
    output_path = Path("data/pbp") / f"qb-pbp-{posteam}-{week}.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
      f.write("// file generated by pbp_qb.py\n\n")
      f.write("export const qbPBPWk" + str(week) + posteam + "= ")
      json.dump(filtered, f, indent=2)
      f.write(" as const;\n")

    print(f"Created file {output_path} with {len(filtered)} " + "plays")

  except Exception as e:
    raise RuntimeError(
        f"Failed to generate PBP for {posteam} week {week}"
    ) from e
