import json
import polars as pl
import nflreadpy as nfl
from pathlib import Path
from typing import Literal

IStatType = Literal["passing", "receiving", "rushing"]

def parse_ngs(statType: IStatType, outputFileName: str, variableName: str):
    """
    Fetch current-season next-gen stats and write them to a .ts file
    """
    try:
        # Fetch next-gen stats (current season by default)
        player_stats = nfl.load_nextgen_stats(stat_type=statType).to_dicts()

        # Write the data to a TypeScript file
        output_path = Path("scripts/weekly/generated-files") / f"{outputFileName}.ts"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("// file generated by fetch_ngs.py\n\n")
            f.write("export const " + variableName + " = ")
            json.dump(player_stats, f, indent=2)
            f.write(" as const;\n")
            f.write(";\n")

        print(f"Created file {output_path} with {len(player_stats)} " + statType)

    except Exception as e:
        print(f"ERROR: {e}")
        raise