import json
import nflreadpy as nfl
from pathlib import Path
from typing import Literal

IPostTeam = Literal[
  "ARI",
  "ATL",
  "BAL",
  "BUF",
  "CAR",
  "CHI",
  "CIN",
  "CLE",
  "DAL",
  "DEN",
  "DET",
  "GB",
  "HOU",
  "IND",
  "JAX",
  "KC",
  "LA",
  "LAC",
  "LAR",
  "LV",
  "MIA",
  "MIN",
  "NE",
  "NO",
  "NYG",
  "NYJ",
  "OAK",
  "PHI",
  "PIT",
  "SD",
  "SEA",
  "SF",
  "STL",
  "TB",
  "TEN",
  "WAS",
  ]

def parse_pbp_qb(posTeam: IPostTeam, week: int):
  try:
    pbp_qb_stats = nfl.load_pbp()

    filtered = pbp_qb_stats.filter(
      (pbp_qb_stats["posteam"] == posTeam) &
      (pbp_qb_stats["pass"] == 1) &
      (pbp_qb_stats["play_type"] == "pass") &
      (pbp_qb_stats["play_type_nfl"] == "PASS") &
      (pbp_qb_stats["week"] == week)
    ).to_dicts()

    # Write the data to a TypeScript file
    output_path = Path("scripts/generated-files") / f"qb-pbp.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
      f.write("// file generated by pbp_qb.py\n\n")
      f.write("export const " + "qbPBP" + " = ")
      json.dump(filtered, f, indent=2)
      f.write(";\n")

    print(f"Created file {output_path} with {len(filtered)} " + "pbp")

  except Exception as e:
    print(f"ERROR: {e}")
    raise
