import json
from api_authorisation import api

def parse_teams():
  """
    Fetch NFL teams via the API, convert them to dictionaries,
    and write to a TypeScript file (scripts/team-data.ts).
  """
  try:
    # Fetch NFL teams data
    data = api.nfl.teams.list()
    if not hasattr(data, "data"):
      raise ValueError("API response missing 'data' attribute")

    # Convert each team to a dictionary using Pydantic v2+ `.model_dump()`
    team_data = [team.model_dump() for team in data.data]

    # Write the data to a TypeScript file
    output_path = "scripts/team-data.ts"
    with open(output_path, "w", encoding="utf-8") as f:
      f.write("// file generated by fetch-qb-data.py\n")
      f.write("\n")
      f.write("export const teamData = ")
      json.dump(team_data, f, indent=2)
      f.write("\n")
    print(f"Created file {output_path} with {len(team_data)} teams")

  except Exception as e:
    print(f"ERROR: {e}")
    raise
