import json
import nflreadpy as nfl

def parse_teams():
    """
    Fetch NFL teams via the API, convert them to dictionaries,
    and write to a TypeScript file (scripts/team-data.ts).
    """
    try:
        # Fetch data (Polars DataFrame)
        team_data = nfl.load_teams().to_dicts()

        # Write the data to a TypeScript file
        output_path = "scripts/team-data.ts"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("// file generated by fetch-team-data.py\n\n")
            f.write("export const teamData = ")
            json.dump(team_data, f, indent=2)
            f.write(";\n")

        print(f"Created file {output_path} with {len(team_data)} teams")

    except Exception as e:
        print(f"ERROR: {e}")
        raise

parse_teams()
