import json
import os
from balldontlie import BalldontlieAPI
from dotenv import load_dotenv

# Load environment variables from a .env file
load_dotenv()

# Initialize the API
api = BalldontlieAPI(api_key=os.getenv('BALLDONTLIEAPI_KEY'))

# Fetch NFL teams data
data = api.nfl.teams.list()

# Convert each team to a dictionary using the `.model_dump()` method for Pydantic v2+
team_data = [team.model_dump() for team in data.data]  # Using `.model_dump()` to get the dictionary representation

# Write the data to a TypeScript file
with open("scripts/team-data.ts", "w") as f:
    f.write("/**\n")
    f.write("* file generated by fetch-qb-data.py\n")
    f.write("*/\n")
    f.write("export const data = ")
    f.write(json.dumps(team_data, indent=2))  # Now it's serializable
    f.write(";\n")
