import json
import polars as pl
import nflreadpy as nfl

def parse_qbs():
    """
    Fetch current-season weekly QB stats and write them to scripts/qb-data-weekly.ts
    """
    try:
        # Fetch player stats (current season by default)
        player_stats = nfl.load_player_stats(summary_level="week")

        # Filter to QBs
        qb_data = (
            player_stats
            .filter(pl.col("position") == "QB")
            .to_dicts()
        )

        # Write the data to a TypeScript file
        output_path = "scripts/qb-data-weekly.ts"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("// file generated by fetch-qb-data-weekly.py\n\n")
            f.write("export const qbDataWeekly = ")
            json.dump(qb_data, f, indent=2)
            f.write(";\n")

        print(f"Created file {output_path} with {len(qb_data)} QBs")

    except Exception as e:
        print(f"ERROR: {e}")
        raise

parse_qbs()
